version: '3'
services:
  backend:
    container_name: addInBackend
    build:
      context: ./addInBackend
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - "9443:9443"
    env_file:
      - ./addInBackend/config.env
  
  frontend:
    container_name: addInFrontend
    build:
      context: ./addInFrontend
      dockerfile: ./Dockerfile
    environment:
      BACKEND_URL: https://raiatea.cisco.com:9443/addin/v1
    ports:
      - "443:443"

  redis:
    container_name: redis
    image: redis:latest
    environment:
      REDIS_PASSWORD: outlookaddinDB
    volumes:
      - redis-db-data:/data
    ports:
      - "6379:6379"
    restart: always

  redisInsight:
    container_name: redisInsight
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    restart: always

volumes:
  redis-db-data:
